<?php
session_start();
$userinfo=$_SESSION["loginfo"];
$uid=$_SESSION["userid"];
if(md5("validuserandpassword")!=$userinfo)
{
	header("location:loginpage.php");
}
$usertype=$_SESSION['vendor_type'];
?>